In [34]:
import random
import time
import numpy as np
import json
import sys

# Importamos codigos .py
import movements as mov
import constants as c

def read_json(filename):
    with open(filename) as json_file:
        data = json.load(json_file)
    return data

log = read_json(c.FICHERO_LOG)
print(log)

{'mat': [[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 2], [0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [2, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 2], [2, 0, 0, 0, 0, 0]], [[2, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [4, 0, 0, 0, 0, 2]], [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 4], [2, 0, 0, 0, 0, 0], [4, 0, 0, 0, 0, 2]], [[2, 0, 0, 0, 0, 4], [4, 0, 0, 0, 0, 2], [0, 0, 0, 0, 4, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], [[2, 4, 0, 0, 0, 0], [4, 2, 0, 0, 0, 0], [4, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 2, 0, 0, 0]], [[0, 0, 0, 0, 2, 4], [2, 0, 0, 0, 4, 2], [0, 0, 0, 0, 0, 4], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 2]], [[0, 0, 0, 0, 0, 0], [0, 4, 0, 0, 0, 0], [0, 0, 0, 0, 0, 4], [0, 0, 0, 0, 0, 2], [0, 0, 0, 0, 2, 4], [2, 0, 0, 0, 4, 2]], [[0, 0, 0, 0, 0

In [35]:
log.keys()

dict_keys(['mat', 'mov', 'scores', 'final', 'score'])

In [36]:
len(log["mat"])

25

In [37]:
len(log["mov"])

25

In [38]:
len(log["scores"])

25

In [39]:
mats = log["mat"]

In [40]:
np.array(mats[0])

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0]])

In [24]:
np.array(mats[1])

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2],
       [2, 0, 0, 0, 0, 0]])

In [25]:
np.array(mats[2])

array([[2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 2]])

In [26]:
np.array(mats[3])

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4],
       [2, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 2]])

In [27]:
movs = log["mov"]

In [28]:
movs[1]

'left'

In [29]:
movs[2]

'down'

In [30]:
movs[3]

'down'

In [31]:
log["scores"][0]

0

In [33]:
[x for x in range(1,4)]

[1, 2, 3]

In [41]:
for itera in range(1, len(log["mat"])):
    print(log["mat"][itera])

[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [2, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 2], [2, 0, 0, 0, 0, 0]]
[[2, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [4, 0, 0, 0, 0, 2]]
[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 4], [2, 0, 0, 0, 0, 0], [4, 0, 0, 0, 0, 2]]
[[2, 0, 0, 0, 0, 4], [4, 0, 0, 0, 0, 2], [0, 0, 0, 0, 4, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]
[[2, 4, 0, 0, 0, 0], [4, 2, 0, 0, 0, 0], [4, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 2, 0, 0, 0]]
[[0, 0, 0, 0, 2, 4], [2, 0, 0, 0, 4, 2], [0, 0, 0, 0, 0, 4], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 2]]
[[0, 0, 0, 0, 0, 0], [0, 4, 0, 0, 0, 0], [0, 0, 0, 0, 0, 4], [0, 0, 0, 0, 0, 2], [0, 0, 0, 0, 2, 4], [2, 0, 0, 0, 4, 2]]
[[0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 0, 4], [0, 0, 0, 0, 0, 4], [0, 0, 0, 0, 0, 2], [0, 0, 0, 0, 2, 4], [0, 0, 0, 2, 4, 2]]
[[0, 2, 0, 2, 2, 8], [0, 0, 0, 0