In [21]:
import numpy as np

In [1]:
import random
from tkinter import Frame, Label, CENTER

# Importamos codigos .py
import logic
import constants as c


class GameGrid(Frame):
    def __init__(self):
        Frame.__init__(self)

        self.grid()
        self.master.title('2048')
        self.master.bind("<Key>", self.key_down)

        # self.gamelogic = gamelogic
        self.commands = {c.KEY_UP: logic.up, c.KEY_DOWN: logic.down,
                         c.KEY_LEFT: logic.left, c.KEY_RIGHT: logic.right,
                         c.KEY_UP_ALT: logic.up, c.KEY_DOWN_ALT: logic.down,
                         c.KEY_LEFT_ALT: logic.left,
                         c.KEY_RIGHT_ALT: logic.right}

        self.grid_cells = []
        self.init_grid()
        self.init_matrix()
        self.update_grid_cells()

        self.mainloop()

    def init_grid(self):
        background = Frame(self, bg=c.BACKGROUND_COLOR_GAME,
                           width=c.SIZE, height=c.SIZE)
        background.grid()

        for i in range(c.GRID_LEN):
            grid_row = []
            for j in range(c.GRID_LEN):
                cell = Frame(background, bg=c.BACKGROUND_COLOR_CELL_EMPTY,
                             width=c.SIZE / c.GRID_LEN,
                             height=c.SIZE / c.GRID_LEN)
                cell.grid(row=i, column=j, padx=c.GRID_PADDING,
                          pady=c.GRID_PADDING)
                t = Label(master=cell, text="",
                          bg=c.BACKGROUND_COLOR_CELL_EMPTY,
                          justify=CENTER, font=c.FONT, width=5, height=2)
                t.grid()
                grid_row.append(t)

            self.grid_cells.append(grid_row)

    def gen(self):
        return random.randint(0, c.GRID_LEN - 1)

    def init_matrix(self):
        self.matrix = logic.new_game(4)
        self.history_matrixs = list()
        self.matrix = logic.add_two(self.matrix)
        self.matrix = logic.add_two(self.matrix)

    def update_grid_cells(self):
        for i in range(c.GRID_LEN):
            for j in range(c.GRID_LEN):
                new_number = self.matrix[i][j]
                if new_number == 0:
                    self.grid_cells[i][j].configure(
                        text="", bg=c.BACKGROUND_COLOR_CELL_EMPTY)
                else:
                    self.grid_cells[i][j].configure(text=str(
                        new_number), bg=c.BACKGROUND_COLOR_DICT[new_number],
                        fg=c.CELL_COLOR_DICT[new_number])
        self.update_idletasks()

    def key_down(self, event):
        key = repr(event.char)
        if key == c.KEY_BACK and len(self.history_matrixs) > 1:
            self.matrix = self.history_matrixs.pop()
            self.update_grid_cells()
            print('back on step total step:', len(self.history_matrixs))
        elif key in self.commands:
            self.matrix, done = self.commands[repr(event.char)](self.matrix)
            if done:
                self.matrix = logic.add_two(self.matrix)
                # record last move
                self.history_matrixs.append(self.matrix)
                self.update_grid_cells()
                done = False
                if logic.game_state(self.matrix) == 'win':
                    self.grid_cells[1][1].configure(
                        text="You", bg=c.BACKGROUND_COLOR_CELL_EMPTY)
                    self.grid_cells[1][2].configure(
                        text="Win!", bg=c.BACKGROUND_COLOR_CELL_EMPTY)
                if logic.game_state(self.matrix) == 'lose':
                    self.grid_cells[1][1].configure(
                        text="You", bg=c.BACKGROUND_COLOR_CELL_EMPTY)
                    self.grid_cells[1][2].configure(
                        text="Lose!", bg=c.BACKGROUND_COLOR_CELL_EMPTY)

    def generate_next(self):
        index = (self.gen(), self.gen())
        while self.matrix[index[0]][index[1]] != 0:
            index = (self.gen(), self.gen())
        self.matrix[index[0]][index[1]] = 2




In [2]:
gamegrid = GameGrid()

In [92]:
#
# CS1010FC --- Programming Methodology
#
# Mission N Solutions
#
# Note that written answers are commented out to allow us to run your
# code easily while grading your problem set.
import random

#######
#Task 1a#
#######

# [Marking Scheme]
# Points to note:
# Matrix elements must be equal but not identical
# 1 mark for creating the correct matrix

# Inicializa la matrix en blanco (4x4) lista de listas
def new_game(n):
    matrix = []

    for i in range(n):
        matrix.append([0] * n)
    return matrix

###########
# Task 1b #
###########

# [Marking Scheme]
# Points to note:
# Must ensure that it is created on a zero entry
# 1 mark for creating the correct loop


def add_two(mat):
    a = random.randint(0, len(mat)-1)
    b = random.randint(0, len(mat)-1)
    while(mat[a][b] != 0):
        # Si ya existe esa posicion(ya hay un 2), elige otra
        a = random.randint(0, len(mat)-1)
        b = random.randint(0, len(mat)-1)
    mat[a][b] = 2 #siempre inicializamos el juego con 2 numeros 2
    return mat

###########
# Task 1c #
###########

# [Marking Scheme]
# Points to note:
# Matrix elements must be equal but not identical
# 0 marks for completely wrong solutions
# 1 mark for getting only one condition correct
# 2 marks for getting two of the three conditions
# 3 marks for correct checking


def game_state(mat):
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            if mat[i][j] == 2048:
                return 'win'
    for i in range(len(mat)-1):
        # intentionally reduced to check the row on the right and below
        # more elegant to use exceptions but most likely this will be their solution
        for j in range(len(mat[0])-1):
            if mat[i][j] == mat[i+1][j] or mat[i][j+1] == mat[i][j]:
                return 'not over'
    for i in range(len(mat)):  # check for any zero entries
        for j in range(len(mat[0])):
            if mat[i][j] == 0:
                return 'not over'
    for k in range(len(mat)-1):  # to check the left/right entries on the last row
        if mat[len(mat)-1][k] == mat[len(mat)-1][k+1]:
            return 'not over'
    for j in range(len(mat)-1):  # check up/down entries on last column
        if mat[j][len(mat)-1] == mat[j+1][len(mat)-1]:
            return 'not over'
    return 'lose'

###########
# Task 2a #
###########

# [Marking Scheme]
# Points to note:
# 0 marks for completely incorrect solutions
# 1 mark for solutions that show general understanding
# 2 marks for correct solutions that work for all sizes of matrices


def reverse(mat):
    new = []
    for i in range(len(mat)):
        new.append([])
        for j in range(len(mat[0])):
            new[i].append(mat[i][len(mat[0])-j-1])
    return new

###########
# Task 2b #
###########

# [Marking Scheme]
# Points to note:
# 0 marks for completely incorrect solutions
# 1 mark for solutions that show general understanding
# 2 marks for correct solutions that work for all sizes of matrices


def transpose(mat):
    new = []
    for i in range(len(mat[0])):
        new.append([])
        for j in range(len(mat)):
            new[i].append(mat[j][i])
    return new

##########
# Task 3 #
##########

# [Marking Scheme]
# Points to note:
# The way to do movement is compress -> merge -> compress again
# Basically if they can solve one side, and use transpose and reverse correctly they should
# be able to solve the entire thing just by flipping the matrix around
# No idea how to grade this one at the moment. I have it pegged to 8 (which gives you like,
# 2 per up/down/left/right?) But if you get one correct likely to get all correct so...
# Check the down one. Reverse/transpose if ordered wrongly will give you wrong result.


def cover_up(mat):
    new = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
    done = False
    for i in range(4):
        count = 0
        for j in range(4):
            if mat[i][j] != 0:
                new[i][count] = mat[i][j]
                if j != count:
                    done = True
                count += 1
    return (new, done)


def merge(mat):
    done = False
    for i in range(4):
        for j in range(3):
            if mat[i][j] == mat[i][j+1] and mat[i][j] != 0:
                mat[i][j] *= 2
                mat[i][j+1] = 0
                done = True
    return (mat, done)


def up(game):
    print("up")
    # return matrix after shifting up
    game = transpose(game)
    game, done = cover_up(game)
    temp = merge(game)
    game = temp[0]
    done = done or temp[1]
    game = cover_up(game)[0]
    game = transpose(game)
    return (game, done)


def down(game):
    print("down")
    game = reverse(transpose(game))
    game, done = cover_up(game)
    temp = merge(game)
    game = temp[0]
    done = done or temp[1]
    game = cover_up(game)[0]
    game = transpose(reverse(game))
    return (game, done)





def right(game):
    print("right")
    # return matrix after shifting right
    game = reverse(game)
    game, done = cover_up(game)
    temp = merge(game)
    game = temp[0]
    done = done or temp[1]
    game = cover_up(game)[0]
    game = reverse(game)
    return (game, done)


# DAVID
def transpose2(game):
    return np.array(game).transpose().tolist()

In [4]:
import random
from collections import Counter

In [5]:
Counter([random.randint(0, 4) for _ in range(100)])

Counter({2: 19, 4: 11, 0: 25, 1: 23, 3: 22})

In [6]:
def new_game(n):
    matrix = []

    for i in range(n):
        matrix.append([0] * n)
    return matrix

In [8]:
mat = new_game(4)

In [9]:
def add_two(mat):
    a = random.randint(0, len(mat)-1)
    b = random.randint(0, len(mat)-1)
    while(mat[a][b] != 0):
        a = random.randint(0, len(mat)-1)
        b = random.randint(0, len(mat)-1)
    mat[a][b] = 2
    return mat

In [11]:
x = add_two(mat)

In [14]:
x[1][1]

0

In [17]:
import tkinter as tk
import time

top = tk.Tk()

def addText():
    # make first change
    oldText = L.cget("text")
    newText = oldText + '\nfirst change'
    L.configure(text=newText)

    # wait 2 seconds
    top.update_idletasks()
    time.sleep(2)

    # make second change
    newText += '\nsecond change'
    L.configure(text=newText)

B = tk.Button(top, text ="Change text", command = addText)
L = tk.Label(top,text='orignal text')

B.pack()
L.pack()
top.mainloop()

In [18]:
time.sleep(5)

In [34]:
tomat(up(mat))

up


array([[0, 0, 2, 2],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Testing UP / DOWN

In [173]:
def arrow_mat(x):
    return np.array(x[0])

def viewmat(x):
    return np.array(x)

In [274]:
def displacement_numbers(mat):
    new = new_game(GRID_LEN) # crea una matrix de 0 de AxA (donde A es la GRID_LEN)
    done = False
    for i in range(GRID_LEN):
        # Inspecciona una fila
        count = 0
        for j in range(GRID_LEN):
            # Si en esa fila hay un elemento no nulo
            if mat[i][j] != 0:
                # Pone ese elemento en la posicion count (columna), donde esta vendra determinada por si
                # en esa fila, previamente, hemos encotrado algun otro elemento NO nulo
                new[i][count] = mat[i][j]
                
                # Solo con que modifiquemos la posicion de una de los numeros, ya contara como un movimiento: done = True
                if j != count:
                    done = True
                    
                # Suma al count una posicion ya que ya se ha movido a la izquerda de todo (columna 0) ese elemento
                count += 1
    return (new, done)

def merge_numbers(mat):
    done = False
    for i in range(GRID_LEN):
        for j in range(GRID_LEN-1): # la ultima columna j, no tiene una columna a su derecha (j+1)
            if mat[i][j] == mat[i][j+1] and mat[i][j] != 0: # si son iguales, y esta igualdad son numeros > 0, se suman
                mat[i][j] *= 2
                mat[i][j+1] = 0 # se deja la de la derecha vacía, esto hace que se necesite hacer otro displacement para llenar ese hueco
                # esto tambien hace que al leer la siguiente columna, se lea un 0, y no el numero que estaba
                done = True
    return (mat, done)

def ro(mat, cw = True, num = 1): #cw: clockwise: True or False, #num: number of rotations
    param_clockise = (1,0)
    if not cw:
        param_clockise = (0,1)
    
    # Cuantas rotaciones hacemos
    rot_mat = mat
    for _ in range(num):
        rot_mat = np.rot90(np.array(rot_mat), axes = param_clockise)
    
    return rot_mat.tolist()      

In [345]:
def add_two(mat, times = 1):
    for _ in range(times):
        a, b = [random.randint(0, len(mat)-1) for _ in range(2)]
        while(mat[a][b] != 0):
            # Si ya existe esa posicion(ya hay un 2), elige otra
            a, b = [random.randint(0, len(mat)-1) for _ in range(2)]
        mat[a][b] = 2 #siempre inicializamos el juego con 2 numeros 2
    return mat

In [346]:
mat = new_game(4)
add_two(mat, times = 2)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 2, 0], [0, 2, 0, 0]]

## Left

In [334]:
def left(game):
    """
    1 - mover al maximo a la izquierda todos los numeros
    2 - Sumamos los iguales dejando 0 en el segundo sumando
    3 - Por seguridad, por si hemos dejado alguno sin desplazar a la izquierda (huecos generados por el merge),
        se vuelve a aplicar sin importar el done o no (no importa si mueve a alguien o no ahora)
    """
    game_disp, done_disp = displacement_numbers(game)
    game_merged, done_merge = merge_numbers(game_disp) #la salida es una tupla (mat, done)
    game_final = displacement_numbers(game_merged)[0]
    return (game_final, done_disp or done_merge)

def down(game):
    """
    C - L - UC
    """
    rotate_game = ro(mat) #rotate clockwise
    left_game, done = left(rotate_game) #apply left
    game_final = ro(left_game, cw = False) #undo the rotation
    return game_final, done

def up(game):
    """
    UC - L - C
    """
    rotate_game = ro(mat, cw = False) #rotate anti-clockwise
    left_game, done = left(rotate_game) #apply left
    game_final = ro(left_game) #undo the rotation
    return game_final, done

def right(game):
    """
    C - C - L - UC - UC
    """
    rotate_game = ro(mat,cw=True, num =2) #double rotation
    left_game, done = left(rotate_game) #apply left
    game_final = ro(left_game, cw = False, num = 2) #undo the rotation
    return game_final, done

In [403]:
# Moviment 0
GRID_LEN = 3

mat = new_game(GRID_LEN)
x = add_two(mat)
x = add_two(mat)

In [338]:
mat[1][3] = 3
mat[1][1] = 2
mat[1][4] = 3
mat[1][5] = 4
mat[3][1] = 5
mat[3][4] = 5

In [386]:
mat = [[0, 0, 1, 4], [0, 4, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [387]:
max(mat)

[0, 4, 0, 0]

In [391]:
class TEST():
    
    def prova(n):
        print("HOLA")

In [398]:
a = ["test", "prova"]

In [399]:
MOVEMENTS = ["Down","Left", "Up", "Right"]
FUNS = [x.lower() for x in MOVEMENTS]

In [400]:
FUNS

['down', 'left', 'up', 'right']

In [393]:
funcio = getattr(TEST, a[1])

In [405]:
getattr?

In [404]:
left(mat)

([[4, 0, 0], [0, 0, 0], [0, 0, 0]], True)

In [357]:
np.random.choice?

In [349]:
viewmat(mat)

array([[0, 0, 0, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [372]:
[1,2,3,4].pop(-2
             )

3

In [340]:
arrow_mat(up(mat))

array([[0, 2, 2, 3, 3, 4],
       [0, 5, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [341]:
arrow_mat(right(mat))

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 6, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 2, 5],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [342]:
arrow_mat(down(mat))

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 3, 0],
       [0, 5, 2, 3, 5, 4]])